onlinestore/home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'

urlpatterns = [
    url('^$' , views.index , name = 'home'),
    url('details/(?P<id>[\d]+)/',views.details , name="details"),
    url('show/' , views.show , name = 'show'),
    # url('show/' , views.show , name = 'error'),
]

onlinestore/login/urls.py
from django.conf.urls import url , include
from django.urls import path
from . import views

app_name = "login"

urlpatterns = [

     url('' , views.login , name="login"),
     url('logout$' , views.login , name="signout"),
]

onlinestore/onlinestore/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url , include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url('admin/', admin.site.urls),
    url('' ,include('home.urls')),
    url('signup/' ,include('signup.urls')),
    url('login/' ,include('login.urls')),
    url('orders/' ,include('orders.urls')),
    # url('show/' , include('error.urls')),
] +static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

onlinestore/orders/urls.py
from django.conf.urls import url , include
from . import views


app_name = "orders"
urlpatterns = [
    url('^$' , views.orders , name="ordersGoods"),
    url("cart/delete/" , views.delete , name="delete"),
     url('cart/' , views.displayCart , name="displayCart"),
     url('buy/' , views.buy , name="buyGoods"),
]

onlinestore/home/models.py
from django.db import models
# Create your models here.
class Store_items(models.Model):
    itemId = models.AutoField(primary_key=True)
    ownerEmail = models.EmailField(max_length = 50)
    itemTitle = models.CharField(max_length = 50)
    BuiltType = models.CharField(max_length = 50)
    price = models.IntegerField()
    ownerPhone = models.CharField(max_length = 50)
    pic = models.ImageField(max_length = 100 , default = "None")
    post_time = models.DateTimeField(auto_now_add=True)
    bought_status = models.BooleanField(default = False , max_length = 3)
    description = models.CharField(max_length = 200)

    class Meta:
        db_table = "Store_items"

onlinestore/home/views.py
from django.shortcuts import render , redirect
from home.models import Store_items
# Create your views here.

def index(request):
    try:
        request.session['username']
    except Exception as e:
        return redirect("/login/")
    else:
        if request.method == "POST":
            #get the data from the browser
            email = request.POST['ownerEmail']
            title = request.POST['itemTitle']
            type = request.POST['BuiltType']
            price = request.POST['price']
            phone = request.POST['ownerPhone']
            pic = request.FILES['pic']
            description = request.POST['description']
            # status = request.POST['bought_status']
            try:
                obj =Store_items(ownerEmail = email ,itemTitle =title , BuiltType =type , price =price , ownerPhone=phone, pic=pic , description = description)
                obj.save()
            except Exception as e:
                print("error occured")
                print( e)
                return render(request,"./add.html")

            else:
                return redirect("/show")

        else:
            return render(request , './home/add.html')

def show(request):
    allItems = Store_items.objects.all()
    return render(request,"./home/index.html",{'allItems':allItems})



def details(request, id):
    print("The app is not found")
    items = Store_items.objects.get(itemId = id)
    # print(items.itemId)
    return render(request,'./home/details.html', {'items':items})

onlinestore/home/templates/home/add.html
{% extends './base.html' %}
  {% block body %}
    <div class="add">
      	  <section class="container grey-text">
      		<h4 class="center">Add your items for sell</h4>
      		<form class="white" action="{% url 'home:home' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
      			<label>Your Email:</label>
      			<input type="email" name="ownerEmail" value="">
      			<!-- <div class="red-text"></div> -->
            <label>Phone Number:</label>
            <input type="text" name="ownerPhone" value="">
            <!-- <div class="red-text"></div> -->
      			<label>Item Title :</label>
      			<input type="text" name="itemTitle" value="">
      			<!-- <div class="red-text"></div> -->
      			<label>Material Built Type:</label>
      			<input type="text" name="BuiltType" value="">
      			<!-- <div class="red-text"></div> -->
            <label>Description :</label>
            <input type="text" name="description" value="">
            <!-- <div class="red-text"></div> -->
            <label>Item Price :</label>
            <input type="number" name="price" value="">
            <!-- <div class="red-text"></div> -->
            <!-- <label>Item Image :</label>
            <input type="file" name="pic" value=""> -->
            <div class="input-group mb-3">
              <!-- <div class="input-group-prepend">
                <span class="input-group-text" id="inputGroupFileAddon01">Upload</span>
              </div> -->
              <div class="custom-file">
                <input type="file" name="pic" class="custom-file-input" id="inputGroupFile01" aria-describedby="inputGroupFileAddon01">
                <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
              </div>
           </div>
            <!-- <div class="red-text"></div> -->
      			<div class="center">
      				<input type="submit" name="submit" value="submit" class="btn brand z-depth-0.9">
      			</div>
      		</form>
      	</section>
    </div>
  {% endblock %}

onlinestore/home/templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <meta charset="utf-8">
  <head>
  {% block top %}

	<title>online store</title>
  <link rel="stylesheet" type="text/css" href="{% static './home/css/bootstrap.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static './home/css/materialize.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static './home/css/style.css' %}">
  <!-- <link rel="stylesheet" type="text/css" href="{% static './home/js/main.js' %}"> -->
	<style type="text/css" >
        		.brand{
        			background: #cbb09c !important;
        		}
        		.brand-text{
        			color: #cbb09c !important;

        		}
            .container{

            }
        		nav{
        			background:transparent;
        		}
        		form{
        			max-width: 460px;
        			margin: 20px auto;
        			padding: 20px;
        		}
            .details{
              padding-top: 50px;
              margin-left: 18%;
              width:50%
              /* position:absolute; */
            }
            .details_img{
              height: 300px;
              width: 350px;
              position: relative;
              margin-left: 25%;
            }

	</style>
  </head>


{% endblock %}
<body>
    {%  block header %}
  <nav class="white-z-depth-0">
  		<div class="container">
        <a href="{% url 'home:show' %}"class="mr-1.5 bg-danger btn">Home</a>
        <a href="{% url 'orders:displayCart' %}"class="mr-1.5 bg-danger btn">Cart</a>
        {% if username %}
        <a href="{% url 'login:signout' %}"class="mr-1.5 bg-danger btn">Sign Out</a>
        {% else %}
        <a href="{% url 'login:login' %}"class="mr-1.5 bg-danger btn">Login</a>
        {% endif %}
  			<ul id="nav-mobile" class="right hide-on-small-and-down">
  				<li><a href="{% url 'home:home' %}" class="btn brand z-depth-0">Add Items</a></li>
  			</ul>
  		</div>
	</nav>
    {% endblock %}
    {%  block body %}
    <h1>Nothing yet</h1>
    {% endblock %}
    {%  block footer %}
          <footer class="section">
          	<div class="center grey-text">Copyright steve's  store 2020</div>
          </footer>
    {% endblock %}

  </body>
</html>

onlinestore/home/templates/home/details.html
{% extends './base.html' %}

{% block body %}
<div class="card center details"  >
  <h5 class="card-title">Buy goods with us Today</h5>
  <img src="/media/{{items.pic}}" class="card-img-top image-fluid details_img" alt="details for image">
  <div class="card-body">
    <h5 class="card-title">{{ items.itemTitle }}</h5>
    <p class="card-text"><b>Description : </b>  {{ items.description }}</p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item"><a href="mailto:{{ items.ownerEmail }}">Owner Email ;{{ items.ownerEmail }}</a></li>
    <li class="list-group-item" ><a href="https://api.whatsapp.com/send?phone={{ items.ownerPhone }}">Owner Phone :{{ items.ownerPhone }}</a></li>
    <li class="list-group-item">Ii It Bought: {{ items.bought_status }}</li>
    <!-- <li class="list-group-item"></li> -->
    <!-- <li class="list-group-item"></li> -->
  </ul>
  <div class="card-body">
    <a href="{% url 'home:show' %}" class="card-link btn btn-success">Back Home</a>
    <a href="{% url 'orders:buyGoods' %}" class="card-link btn btn-primary ">Buy Item</a>
    <!-- {% csrf_token %} -->
    <a  class=" btn btn-success card-link" onclick="showHint({{items.itemId}});">Add to cart</a>
<!-- href="{% url 'orders:ordersGoods' %}" -->
<script type="text/javascript">
    function showHint(id) {
    var xmlhttp = new XMLHttpRequest();
    xmlhttp.onreadystatechange = function() {
      if (this.readyState == 4 && this.status == 200) {
        // id =
        // document.getElementById("").innerHTML = this.responseText;
        alert(this.responseText);
      }
    };
    // xmlhttp.open("POST" ,"/orders/, true);
    xmlhttp.open("GET" ,"/orders/?id="+id, true);
    // xhttp.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
    // xmlhttp.setRequestHeader('Content-type','application/x-www-form-urlencoded');
    xmlhttp.send();
  }
</script>
  </div>
  <div class="card-footer">
    <small class="text-muted">Posted Time : {{ items.post_time }}</small>
  </div>
</div>
{% endblock %}

onlinestore/home/templates/home/error.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>This is the error Page</title>
  </head>
  <body>
    <div class="wrapper">
      <div class="error">
        <center><h1>The page you were trying to access Got Screwed up</h1></center>
      </div>
      <div class="errorMsg">
        <center><h1>Error is :;  {{e}}</h1></center>
      </div>

    </div>

  </body>
</html>

onlinestore/home/templates/home/index.html
{% extends "./base.html" %}

{% block body %}
  <h4 class="center grey-text">Online Store</h4>
	<div class="container">

  <div class="row">
  <!-- <div class="card-deck"> -->

      {% for allItem in allItems %}
      <div class="col-sm-12 col-md-6 col-lg-4">
        <div class="card">

          <img src="/media/{{allItem.pic}}" class="card-img-top img-fluid img-thumbnail " alt="image">
          <div class="card-body">
            <h5 class="card-title">Item:  {{ allItem.itemTitle }}</h5>
            <p class="card-text"><b>Desc:</b>  {{ allItem.description }}</p>
          </div>
          <div class="card-action ">
                <a class='btn btn-info right-align mr-1.5' href="{% url 'home:details' allItem.itemId %}">Buy Item</a>
                <a class='btn btn-info right-align' href="{% url 'home:details' allItem.itemId %}">More Info</a>
          </div>
          <div class="card-footer">
            <small class="text-muted">{{ allItem.post_time }}</small>
          </div>

       </div>
      </div>
    {% endfor %}
</div>
</div>

{% endblock %}