onlinestore/home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'

urlpatterns = [
    url('^$' , views.index , name = 'home'),
    url('details/(?P<id>[\d]+)/',views.details , name="details"),
    url('show/' , views.show , name = 'show'),
    # url('show/' , views.show , name = 'error'),
]

onlinestore/login/urls.py
from django.conf.urls import url , include
from django.urls import path
from . import views

app_name = "login"

urlpatterns = [

     url('' , views.login , name="login"),
     url('logout$' , views.login , name="signout"),
]

onlinestore/onlinestore/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url , include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url('admin/', admin.site.urls),
    url('' ,include('home.urls')),
    url('signup/' ,include('signup.urls')),
    url('login/' ,include('login.urls')),
    url('orders/' ,include('orders.urls')),
    # url('show/' , include('error.urls')),
] +static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

onlinestore/orders/urls.py
from django.conf.urls import url , include
from . import views


app_name = "orders"
urlpatterns = [
    url('^$' , views.orders , name="ordersGoods"),
    url("cart/delete/" , views.delete , name="delete"),
     url('cart/' , views.displayCart , name="displayCart"),
     url('buy/' , views.buy , name="buyGoods"),
]

onlinestore/orders/models.py
from django.db import models
from home.views import Store_items
from signup.views import SignUser

# Create your models here.
class OrderItems(models.Model):
    orderId = models.AutoField(primary_key=True)
    ownerEmail = models.EmailField(max_length = 50)
    itemId = models.ForeignKey(Store_items , on_delete = models.CASCADE)
    buyerId = models.ForeignKey(SignUser , on_delete = models.CASCADE)
    price = models.IntegerField()
    # itemTitle = models.CharField(max_length = 50)
    # BuiltType = models.CharField(max_length = 50)
    # ownerPhone = models.CharField(max_length = 50)
    # pic = models.ImageField(max_length = 100 , default = "None")
    # post_time = models.DateTimeField(auto_now_add=True)
    # bought_status = models.BooleanField(default = False , max_length = 3)
    # description = models.CharField(max_length = 200)

    class Meta:
        db_table = "OrderItems"

onlinestore/orders/views.py
from django.shortcuts import render , redirect
from signup.models import SignUser
from django.http import HttpResponse
from  home.models import Store_items
from django.core.mail import send_mail
from .models import OrderItems
# Create your views here.
def orders(request):
    # print(request.session["username"])
    # print("\n\n\n\nyeess")
    # print(request.method)
    # print(request.GET['id'])
    if(request.method=="GET"):
        # print(request.method=="GET")
        id = request.GET["id"]

        # print(request.session["items"])
        try:
            # request.session["items"].append("Hello")
            data = Store_items.objects.get(itemId = id)
            price = data.price
            email = data.ownerEmail
            itemId = data.itemId
            user = request.session["username"]
            buyerId = SignUser.objects.get(username = user).userId
            OrderItems.objects.create(ownerEmail = email , itemId_id = itemId , buyerId_id =buyerId , price = price )

            print(data)
            print(request.session["items"])
        except Exception as e:
            print(e)
            print("\n\n\n\n")
            return render(request , "./home/details.html")
        else:
            return HttpResponse("Item added to the cart")
            # return render(request , "./orders/cart.html" , {"data":data})
    else:
        return render(request , "./home/details.html")
    #function to show the items
    # return redirect("/show/")
    # return HttpResponse("<h1>Hello there My people</h2>")

def displayCart(request):
    try:
        request.session["username"]
# print("Hello display cart \n\n\n")

    except Exception as e:
        return redirect("/login/")
    else:
        cartItems = OrderItems.objects.filter(buyerId_id = SignUser.objects.get(username = request.session["username"]).userId)
        return render(request , "orders/cart.html"  , {"cartItems":cartItems , "username":request.session["username"]})


def buy(request):
    #function to buy ordered items
    #function to send receit through mails
    try:
        # print("\n\n\n\n\nYes am here in first trial")
        request.session["username"]
    except Exception as e:
        print("An error Occured" + str(e))
        # print("\n\n\n\n\nYes am here in first trial2")
        return redirect("/login/")
    else:
        try:
            #admin email is stiveckamash@gmail.com
            adminMail = "stiveckamash@gmail.com"
            messageBody = "Hello We Have send you the email with the invoice...Please be carefull When awaiting it to reach you!"
            messageHead = "Invoice List for the ordered Produscts!"
            #check the regestered mail
            checkMail = SignUser.objects.get(username = request.session["username"]).email
            # print(checkMail)
            sendEmail = send_mail(messageHead ,messageBody , checkMail , [adminMail])
        except Exception as e:
            print("Error Occured here "+str(e))
            # return HttpResponse("An error Occured! Please Resubmit Again")
            return render(request , "orders/error.html" , {"e":e})
        else:
            return redirect("/buy")

    return HttpResponse("OOPS!")
def delete(request):
    # print(request.method)
    # print("\n\n\n\n\n")
    #function to remove an item from the cartcd
    if(request.method=="GET"):
        id = request.GET["id"]
        try:
            remove = OrderItems.objects.filter(itemId_id = id).delete()
        except Exception as e:
            return render(request , "orders/error.html" , {"e":e})
            print(e)
        else:
            # print("Removed Successful")
            # return HttpResponse("Item removed Successfully!")
            cartItems = OrderItems.objects.filter(buyerId_id = SignUser.objects.get(username = request.session["username"]).userId)
            return render(request , "orders/cart.html"  , {"cartItems":cartItems , "username":request.session["username"]})


    else:
        return HttpResponse("OOPS! Something Went Wrong!")
        # print("No id")

onlinestore/orders/templates/orders/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <meta charset="utf-8">
  <head>
  {% block top %}

	<title>online store</title>
  <link rel="stylesheet" type="text/css" href="{% static './home/css/bootstrap.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static './home/css/materialize.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static './home/css/style.css' %}">
  <!-- <link rel="stylesheet" type="text/css" href="{% static './home/js/main.js' %}"> -->
	<style type="text/css" >
        		.brand{
        			background: #cbb09c !important;
        		}
        		.brand-text{
        			color: #cbb09c !important;

        		}
            .container{

            }
        		nav{
        			background:transparent;
        		}
        		form{
        			max-width: 460px;
        			margin: 20px auto;
        			padding: 20px;
        		}
            .details{
              padding-top: 50px;
              margin-left: 18%;
              width:50%
              /* position:absolute; */
            }
            .details_img{
              height: 300px;
              width: 350px;
              position: relative;
              margin-left: 25%;
            }

	</style>
  </head>


{% endblock %}
<body>
    {%  block header %}
  <nav class="white-z-depth-0">
  		<div class="container">
        <!-- <h1>{{username}}</h1> -->
        <a href="{% url 'home:show' %}"class="mr-1.5 bg-danger btn">Home</a>
        <a href="{% url 'orders:displayCart' %}"class="mr-1.5 bg-danger btn">Cart</a>
        {% if username %}
        <a href="{% url 'login:signout' %}"class="mr-1.5 bg-danger btn">Sign Out</a>
        {% else %}
        <a href="{% url 'login:login' %}"class="mr-1.5 bg-danger btn">Login</a>
        {% endif %}
  			<ul id="nav-mobile" class="right hide-on-small-and-down">
  				<li><a href="{% url 'home:home' %}" class="btn brand z-depth-0">Add Items</a></li>
  			</ul>
  		</div>
	</nav>
    {% endblock %}
    {%  block body %}
    <h1>Nothing yet</h1>
    {% endblock %}
    {%  block footer %}
          <footer class="section">
          	<div class="center grey-text">Copyright steve's  store 2020</div>
          </footer>
    {% endblock %}

  </body>
</html>

onlinestore/orders/templates/orders/cart.html
    {% extends "./base.html" %}

    {% block body %}
      <h4 class="center grey-text">Online Store</h4>
    	<div class="container">

      <div class="row">
      <!-- <div class="card-deck"> -->

          {% for cartItem in cartItems %}
          <div class="col-sm-6 col-md-4 col-lg-3">
            <div class="card">

              <img src="/media/{{cartItem.itemId.pic}}" class="card-img-top img-fluid img-thumbnail " alt="image">
              <div class="card-body">
                <h5 class="card-title">This is Cart Display for {{ username }}</h5>
                <small><p class="card-text btn btn-info btn-sm"><b>price:</b> KSH. {{ cartItem.price }}</p></small>
                <small><p class="card-text"><b>Type:</b>  {{ cartItem.itemId.BuiltType }}</p></small>
                <small><p class="card-text"><b>Mail:</b>  {{ cartItem.ownerEmail }}</p></small>
                  <small><p class="card-text"><b>Tel:</b>  {{ cartItem.itemId.ownerPhone }}</p></small>
                <small><p class="card-text"><b>Desc:</b>  {{ cartItem.itemId.description }}</p></small>
                {{cartItem.itemId_id}}
              </div>
              <div class="card-action ">
                <small><a class='btn btn-info btn-sm left-align mr-1.5' href="{% url 'home:show' %}">Back </a></small>
                <small><a class='btn btn-danger btn-sm right-align' onclick="showHint({{cartItem.itemId_id}});">del</a></small>
              <!-- href="{% url 'orders:delete'  %}" -->
              </div>
              <div class="card-footer">
                <small class="text-muted">{{ cartItem.post_time }}</small>
              </div>
              <script type="text/javascript">
                  function showHint(id) {
                  var xmlhttp = new XMLHttpRequest();
                  xmlhttp.onreadystatechange = function() {
                    if (this.readyState == 4 && this.status == 200) {
                      // id =
                      // document.getElementById("").innerHTML = this.responseText;
                      alert("Item Removed Successfully!")
                      alert(this.responseText);
                      // alert(id);
                    }
                  };
                  // xmlhttp.open("POST" ,"/orders/, true);
                  xmlhttp.open("GET" , "{% url 'orders:delete'  %}?id="+id, true);
                  // xhttp.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
                  // xmlhttp.setRequestHeader('Content-type','application/x-www-form-urlencoded');
                  xmlhttp.send();
                }
              </script>

           </div>
          </div>
        {% endfor %}
    </div>
    </div>

    {% endblock %}
    <!-- <a class='btn btn-info right-align mr-1.5' href="{% url 'home:details' allItem.itemId %}">Buy Item</a> -->
    <!-- <a class='btn btn-info right-align' href="{% url 'home:details' allItem.itemId %}">More Info</a> -->
    <h1>{{username}}</h1>
    {% for item in cartItems %}
    <h1>{{item.ownerEmail}}</h1>
    <h1>{{item.buyerId_id}}</h1>
    <h1>{{item.itemId_id}}</h1>
    <h1>{{item.orderId}}</h1>
    <img src="/media/{{item.itemId.pic}}" alt="{{item.itemId.pic}}">
    {% endfor %}

onlinestore/orders/templates/orders/error.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>This is the error Page</title>
  </head>
  <body>
    <div class="wrapper">
      <div class="error">
        <center><h1>The page you were trying to access Got Screwed up</h1></center>
      </div>
      <div class="errorMsg">
        <center><h1>Error is :;  {{e}}</h1></center>
      </div>

    </div>

  </body>
</html>