onlinestore/home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'

urlpatterns = [
    url('^$' , views.index , name = 'home'),
    url('details/(?P<id>[\d]+)/',views.details , name="details"),
    url('show/' , views.show , name = 'show'),
    # url('show/' , views.show , name = 'error'),
]

onlinestore/onlinestore/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url , include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url('admin/', admin.site.urls),
    url('' ,include('home.urls')),
    url('signup/' ,include('signup.urls')),
    url('login/' ,include('login.urls')),
    url('orders/' ,include('orders.urls')),
    # url('show/' , include('error.urls')),
] +static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

onlinestore/signup/urls.py
from django.conf.urls import url
from . import views

app_name = "signup"

urlpatterns =[

   url('' , views.signup , name = 'signup')
]

onlinestore/signup/models.py
from django.db import models

# Create your models here.
class SignUser(models.Model):
    userId = models.AutoField(primary_key=True)
    username = models.CharField(max_length = 60  , unique = True)
    fname = models.CharField(max_length = 60)
    lname = models.CharField(max_length = 60)
    email = models.EmailField(max_length = 60 , unique = True)
    password = models.CharField(max_length = 30)

    class Meta:
        db_table = "SignUser"

onlinestore/signup/views.py
from django.shortcuts import render , redirect
#import the table data fields into this PAage
from signup.models import SignUser
# Create your views here.


#create a function to do data saving
def signup(request):
    if request.method=="POST":
        username = request.POST['username']
        email = request.POST["email"]
        fname = request.POST["fname"]
        lname = request.POST["lname"]
        password =request.POST["password"]

        try:
            signupuser = SignUser(username = username , fname = fname , lname = lname  , email=email , password = password)
            signupuser.save()
        except Exception as e:
            print("error occured")
            print(e)
            return render(request , "signup/signup.html")
        else:
            return redirect("/login/")

    else:
        return render(request , "signup/signup.html")

onlinestore/signup/templates/signup/signup.html
{% load static%}
<!DOCTYPE HTML>
<html>
<head>
	<meta   >
	<title>Sign Up PAage</title>
	<link rel="stylesheet" type="text/css" href="{% static './signup/signup.css' %}">

</head>
<body>

 <div id="header">
  <div id="div1" class="fa"></div>
	<form class="box" , id="signupform" action="{% url 'signup:signup' %}" method="post">
    {% csrf_token %}
		<h1> Sign Up page </h1>
		<input type="text" name="username" placeholder="username">
		<input type="text" name="fname" placeholder="First name">
		<input type="text" name="lname" placeholder="econd Name">
		<input type="email" name="email" placeholder="Email">
		<input type="password" name="password" placeholder="password">
		<input type="password" name="cpassword" placeholder="Confirm password">
		<input type="submit"  onclick="signUpCheck()" name=""  value="signup" >
    </form>
    </div>


</body>
<script src="{% static './signup/signup.js' %}" charset="utf-8"></script>
</html>